### ISSUE TITLE
Grafana Rolle schreiben

### ISSUE THREAD

**Issue by DO1JLR** [ffbsee/ffbsee-ansible#2]
s.ffbsee.de sollte auch selber gehostet werden mit open source scripten um das debuggen zu können.

Bitte ansible rolle dafür schreiben und irgendwo vernünftig deployen!

**Comment by DO1JLR** [comment]
Grafana scheint selber ganz gute Ansible Rollen zu haben.... Man könnte sich das mal anschauen!

**Comment by DO1JLR** [comment]
habe begonnen... brauche noch etwas zeit!

**Comment by DEvil0000** [comment]
gibt genug rollen
