### ISSUE TITLE
Monitoring stack

### ISSUE THREAD

**Issue by DO1JLR** [ffbsee/ffbsee-ansible#31]
Grafana wäre geil.

+ Mit Traffic, CPU, RAM, io usw von allen gateways.
+ mit allen infos aus alfred
+ mit mehr cyber
+ in schnell (ohne 1min ladezeit)

**Comment by rtt-mmk** [comment]
guckst du was unter netzwerk[-monitoring](https://github.com/ToolboxBodensee/netzwerk-monitoring) kommst und passt an und deployst. Vorgeschmack: [Auslastung](https://www.bw-cloud.org/de/bwcloud_scope/auslastung) - DISCLAIMER: aber mit Erpressung und Strom einfach mal ziehen erreicht man gar nichts, außer Demotivation!

**Comment by DO1JLR** [comment]
und bin wieder erfolgreich demotiviert.

HEY MATT

HALTE DOCH EINMAL ERFOLGREICH DIE VON DIR GESETZTEN DEADLINES EIN OHNE DAS MAN DICH TRETEN UND DARAN ERINNERN MUSS

KEIN BOCK MEHR

**Comment by DO1JLR** [comment]
https://github.com/ffbsee/netzwerk-monitoring.git liefert 404 :cry:

**Comment by rtt-mmk** [comment]
tja toolbox-bodensee/netzwerk-monitoring wie oben steht nicht mehr
ist aber noch einiges an arbeit in dem repo

**Comment by DO1JLR** [comment]
> tja toolbox-bodensee/netzwerk-monitoring wie oben steht nicht mehr
> ist aber noch einiges an arbeit in dem repo

Ja, merke gerade das das noch weit vor einsatzfähigkeit ist...

Warte noch ein, zwei Monate

**Comment by DEvil0000** [comment]
started something in branch: monitoring
Done:
* installing telegraf
* installing prometheus
* installing grafana
TODO:
* installing freifunk exporter (experimental repo)
* configure ssl for telegraf.. reverse proxy?
* set password for things like telegraf
* more config forr grafana
* double check for prometheus port is localhost only
* reverse proxy grafana
* add grafana dashboards
* add grafana users

**Comment by re4jh** [comment]
### image renderer plugin
thx for your work!
thinking of grafana stuff: there is a grafana image renderer plugin. i suggest to install this one.
so we could render images of grafana charts to include them in the map-viewer later

**Comment by DO1JLR** [comment]
ja, schade das sich Freifunk als so unbrauchbar am Bodensee entwickelt hat.
